apiVersion: v1
kind: Pod
metadata:
  name: api-pod
  labels:
    app: api
spec:
  containers:
    - name: api-container
      image: techspawn2000/shortlet-time-api-job:latest
      ports:
        - containerPort: 3000
